# Generated by Django 4.1.4 on 2022-12-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imageURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
