# Generated by Django 4.1.4 on 2022-12-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_user_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imageURL',
            field=models.CharField(blank=True, default='no image', max_length=400, null=True),
        ),
    ]
