# Generated by Django 4.1.4 on 2022-12-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_user_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.CharField(blank=True, default='no image', max_length=255, null=True),
        ),
    ]
