# Generated by Django 4.1.4 on 2022-12-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_alter_user_imageurl_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imageURL',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
